# Library for GENERIC_REACTION_WHEEL Target
require 'cosmos'
require 'cosmos/script'

#
# Definitions
#
GENERIC_REACTION_WHEEL_CMD_SLEEP = 0.25
GENERIC_REACTION_WHEEL_RESPONSE_TIMEOUT = 5
GENERIC_REACTION_WHEEL_TEST_LOOP_COUNT = 1
GENERIC_REACTION_WHEEL_DEVICE_LOOP_COUNT = 5

#
# Functions
#
def get_GENERIC_REACTION_WHEEL_hk()
    cmd("GENERIC_REACTION_WHEEL GENERIC_REACTION_WHEEL_REQ_HK")
    wait_check_packet("GENERIC_REACTION_WHEEL", "GENERIC_REACTION_WHEEL_HK_TLM", 1, GENERIC_REACTION_WHEEL_RESPONSE_TIMEOUT)
    sleep(GENERIC_REACTION_WHEEL_CMD_SLEEP)
end

def get_GENERIC_REACTION_WHEEL_data()
    cmd("GENERIC_REACTION_WHEEL GENERIC_REACTION_WHEEL_REQ_DATA")
    wait_check_packet("GENERIC_REACTION_WHEEL", "GENERIC_REACTION_WHEEL_DATA_TLM", 1, GENERIC_REACTION_WHEEL_RESPONSE_TIMEOUT)
    sleep(GENERIC_REACTION_WHEEL_CMD_SLEEP)
end

def GENERIC_REACTION_WHEEL_cmd(*command)
    count = tlm("GENERIC_REACTION_WHEEL GENERIC_REACTION_WHEEL_HK_TLM CMD_COUNT") + 1

    if (count == 256)
        count = 0
    end

    cmd(*command)
    get_GENERIC_REACTION_WHEEL_hk()
    current = tlm("GENERIC_REACTION_WHEEL GENERIC_REACTION_WHEEL_HK_TLM CMD_COUNT")
    if (current != count)
        # Try again
        cmd(*command)
        get_GENERIC_REACTION_WHEEL_hk()
        current = tlm("GENERIC_REACTION_WHEEL GENERIC_REACTION_WHEEL_HK_TLM CMD_COUNT")
        if (current != count)
            # Third times the charm
            cmd(*command)
            get_GENERIC_REACTION_WHEEL_hk()
            current = tlm("GENERIC_REACTION_WHEEL GENERIC_REACTION_WHEEL_HK_TLM CMD_COUNT")
        end
    end
    check("GENERIC_REACTION_WHEEL GENERIC_REACTION_WHEEL_HK_TLM CMD_COUNT >= #{count}")
end

def enable_GENERIC_REACTION_WHEEL()
    # Send command
    GENERIC_REACTION_WHEEL_cmd("GENERIC_REACTION_WHEEL GENERIC_REACTION_WHEEL_ENABLE_CC")
    # Confirm
    check("GENERIC_REACTION_WHEEL GENERIC_REACTION_WHEEL_HK_TLM DEVICE_ENABLED == 'ENABLED'")
end

def disable_GENERIC_REACTION_WHEEL()
    # Send command
    GENERIC_REACTION_WHEEL_cmd("GENERIC_REACTION_WHEEL GENERIC_REACTION_WHEEL_DISABLE_CC")
    # Confirm
    check("GENERIC_REACTION_WHEEL GENERIC_REACTION_WHEEL_HK_TLM DEVICE_ENABLED == 'DISABLED'")
end

def safe_GENERIC_REACTION_WHEEL()
    get_GENERIC_REACTION_WHEEL_hk()
    state = tlm("GENERIC_REACTION_WHEEL GENERIC_REACTION_WHEEL_HK_TLM DEVICE_ENABLED")
    if (state != "DISABLED")
        disable_GENERIC_REACTION_WHEEL()
    end
end

def confirm_GENERIC_REACTION_WHEEL_data()
    dev_cmd_cnt = tlm("GENERIC_REACTION_WHEEL GENERIC_REACTION_WHEEL_HK_TLM DEVICE_COUNT")
    dev_cmd_err_cnt = tlm("GENERIC_REACTION_WHEEL GENERIC_REACTION_WHEEL_HK_TLM DEVICE_ERR_COUNT")
    
    get_GENERIC_REACTION_WHEEL_data()
    # Note these checks assume default simulator configuration
    raw_x = tlm("GENERIC_REACTION_WHEEL GENERIC_REACTION_WHEEL_DATA_TLM RAW_GENERIC_REACTION_WHEEL_X")
    check("GENERIC_REACTION_WHEEL GENERIC_REACTION_WHEEL_DATA_TLM RAW_GENERIC_REACTION_WHEEL_Y >= #{raw_x*2}")
    check("GENERIC_REACTION_WHEEL GENERIC_REACTION_WHEEL_DATA_TLM RAW_GENERIC_REACTION_WHEEL_Z >= #{raw_x*3}")

    get_GENERIC_REACTION_WHEEL_hk()
    check("GENERIC_REACTION_WHEEL GENERIC_REACTION_WHEEL_HK_TLM DEVICE_COUNT >= #{dev_cmd_cnt}")
    check("GENERIC_REACTION_WHEEL GENERIC_REACTION_WHEEL_HK_TLM DEVICE_ERR_COUNT == #{dev_cmd_err_cnt}")
end

def confirm_GENERIC_REACTION_WHEEL_data_loop()
    GENERIC_REACTION_WHEEL_DEVICE_LOOP_COUNT.times do |n|
        confirm_GENERIC_REACTION_WHEEL_data()
    end
end

#
# Simulator Functions
#
def GENERIC_REACTION_WHEEL_prepare_ast()
    # Get to known state
    safe_GENERIC_REACTION_WHEEL()

    # Enable
    enable_GENERIC_REACTION_WHEEL()

    # Confirm data
    confirm_GENERIC_REACTION_WHEEL_data_loop()
end

def GENERIC_REACTION_WHEEL_sim_enable()
    cmd("SIM_CMDBUS_BRIDGE GENERIC_REACTION_WHEEL_SIM_ENABLE")
end

def GENERIC_REACTION_WHEEL_sim_disable()
    cmd("SIM_CMDBUS_BRIDGE GENERIC_REACTION_WHEEL_SIM_DISABLE")
end

def GENERIC_REACTION_WHEEL_sim_set_status(status)
    cmd("SIM_CMDBUS_BRIDGE GENERIC_REACTION_WHEEL_SIM_SET_STATUS with STATUS #{status}")
end
